# demo_setup.yml

---
- name: installing nsx agent for application
  hosts: application
  become: yes
  become_user: root

  tasks:
  - name: Get nsx-agent from URL
    get_url: url=http://54.149.112.14/nsx-agent_1.1.0.0.0.7515155_amd64.deb dest=/home/ubuntu/nsx-agent_1.1.0.0.0.7515155_amd64.deb force=yes owner=ubuntu group=ubuntu mode=0755

  - name: install nsx agent debs
    apt: deb=/home/ubuntu/nsx-agent_1.1.0.0.0.7515155_amd64.deb state=present
    ignore_errors: yes

  - name: create a file
    copy: src=./roles/files/public-cloud-config dest=/etc/vmware/nsx/public-cloud-config owner=ubuntu group=ubuntu mode=0644

